### ISSUE TITLE
Rakudostar on chocolatey is outdated

### ISSUE THREAD

**Issue by dominix** [briandfoy/rakudo-star-chocolatey#14]
Hi brian,

rakudostar on chocolatey is in version 2019.03.01  while last release is 2020.07.1
could you sync an update.
thanks, regards.

**Comment by briandfoy** [comment]
The latest rakudostar is 2020.05.1, and that's what's on chocolatey right now. The rakudo (bare) is usually slightly ahead of rakudostar.
